-- 코드를 입력하세요
SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM USER_INFO INFO JOIN ONLINE_SALE SALE
ON INFO.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;