SELECT  YEAR(O.SALES_DATE) YEAR,
        MONTH(O.SALES_DATE) MONTH,
        COUNT(DISTINCT O.USER_ID) PUCHASED_USERS,
        ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*)
                                FROM USER_INFO 
                                WHERE JOINED >= '2021-01-01 00:00:00' 
                                    AND JOINED < '2022-01-01 00:00:00'), 1) PUCHASED_RATIO
FROM  ONLINE_SALE O 
INNER JOIN USER_INFO U
ON U.USER_ID = O.USER_ID
WHERE U.JOINED >= '2021-01-01 00:00:00' 
                                    AND U.JOINED < '2022-01-01 00:00:00'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH