-- 코드를 입력하세요
SELECT HALF.FLAVOR 
FROM FIRST_HALF HALF, ICECREAM_INFO ICE_CREAM
WHERE HALF.FLAVOR = ICE_CREAM.FLAVOR 
AND HALF.TOTAL_ORDER > 3000
AND ICE_CREAM.INGREDIENT_TYPE = 'fruit_based'
ORDER BY HALF.TOTAL_ORDER DESC;