-- 코드를 입력하세요
SELECT USR.USER_ID, USR.NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1," ", STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTR(TLNO, 1, 3), "-", SUBSTR(TLNO, 4, 4), "-", SUBSTR(TLNO, 8)) AS 전화번호
FROM USED_GOODS_BOARD BO JOIN USED_GOODS_USER USR
ON BO.WRITER_ID = USR.USER_ID

GROUP BY BO.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY USR.USER_ID DESC;