-- 코드를 입력하세요
SELECT USER_ID,	NICKNAME, SUM(BO.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD BO JOIN USED_GOODS_USER USR
ON BO.WRITER_ID = USR.USER_ID
WHERE BO.STATUS = "DONE" 
GROUP BY BO.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES