-- 코드를 입력하세요
SELECT SUSER.USER_ID, SUSER.NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD BOARD, USED_GOODS_USER SUSER
WHERE BOARD.WRITER_ID = SUSER.USER_ID AND BOARD.STATUS = 'DONE'
GROUP BY WRITER_ID 
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;