-- 코드를 입력하세요
SELECT PRO.PRODUCT_CODE, SUM(SALE.SALES_AMOUNT) * PRO.PRICE AS SALES
FROM PRODUCT PRO INNER JOIN OFFLINE_SALE SALE
ON PRO.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRO.PRODUCT_CODE;