-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALE.SALES_AMOUNT) * PRO.PRICE AS SALES
FROM PRODUCT PRO, OFFLINE_SALE SALE
WHERE PRO.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY SALE.PRODUCT_ID
ORDER BY SALES DESC, PRO.PRODUCT_CODE;