-- 코드를 입력하세요
SELECT APP.APNT_NO, PAT.PT_NAME, PAT.PT_NO, DOC.MCDP_CD, DOC.DR_NAME, APP.APNT_YMD
FROM PATIENT PAT  
    INNER JOIN APPOINTMENT APP ON PAT.PT_NO = APP.PT_NO 
    INNER JOIN DOCTOR DOC ON APP.MDDR_ID = DOC.DR_ID
WHERE APP.MCDP_CD = 'CS' AND APP.APNT_CNCL_YN = 'N' AND YEAR(APP.APNT_YMD) = 2022 AND
MONTH(APP.APNT_YMD) = 04 AND DAY(APP.APNT_YMD) = 13
ORDER BY APP.APNT_YMD; 
